name: create configuration settings
# Export solution from DEV environment
# unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
    inputs:
      #Do Not change these values
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default: SelfServiceAgent
      solution_folder:
        description: 'staging the unpacked solution folder before check-in *do not change*'
        required: true
        default: out/solutions/
      solution_target_folder:
       description: 'folder name to be created and checked in *do not change*'
       required: true
       default: solutions/
      solution_settings_folder:
       description: 'folder name to be created for settings JSON file and checked in *do not change*'
       required: true
       default: settings/
      UAT_solution_settings_name:
       description: 'folder name to be created for settings JSON file and checked in *do not change*'
       required: true
       default: DeploymentSettings-UAT.json
      PROD_solution_settings_name:
       description: 'folder name to be created for settings JSON file and checked in *do not change*'
       required: true
       default: DeploymentSettings-Prod.json

env:
#edit your values here
  ENVIRONMENT_URL: ${{ secrets.ENVIRONMENT_URL }}
  CLIENT_ID: ${{ secrets.POWERPLATFORM_CLIENT_ID }}
  TENANT_ID: ${{ secrets.POWERPLATFORM_TENANT_ID }}
permissions:
  contents: write

jobs:
  create-settings:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1
      
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.POWERPLATFORMSPN }}
        tenant-id: ${{env.TENANT_ID}}

    - name: export-solution action for managed solution
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.POWERPLATFORMSPN }}
        tenant-id: ${{env.TENANT_ID}}
        managed: true
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}_managed.zip

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Adjust version if needed
 
    - name: Install Microsoft PowerApps CLI Tool
      run: dotnet tool install --global Microsoft.PowerApps.CLI.Tool

    - name: use pac command to generate Deployment settings file for UAT and Prod environment
      run: |
        pac solution create-settings --solution-zip ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}_managed.zip --settings-file settings/${{ github.event.inputs.UAT_solution_settings_name}}
        pac solution create-settings --solution-zip ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}_managed.zip --settings-file settings/${{ github.event.inputs.Prod_solution_settings_name}}

    - name: branch-solution for managed, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v1
      with:
        solution-folder: ${{ github.event.inputs.solution_settings_folder }}
        solution-target-folder: ${{ github.event.inputs.solution_settings_folder }}
        repo-token: ${{ secrets.GH_PAT }}
        allow-empty-commit: true
