name: create connections in Higher environment
# Create Connection in higher environment
# using pac command

on:
  workflow_dispatch:
    inputs:
      #Do Not change these values
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default: SelfServiceAgent

env:
#edit your values here
  ENVIRONMENT_URL: ${{ secrets.BUILD_ENVIRONMENT_URL }}
  CLIENT_ID: ${{ secrets.POWERPLATFORM_CLIENT_ID }}
  TENANT_ID: ${{ secrets.POWERPLATFORM_TENANT_ID }}
permissions:
  contents: write

jobs:
  create-settings:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1
      
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.POWERPLATFORMSPN }}
        tenant-id: ${{env.TENANT_ID}}

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Adjust version if needed
 
    - name: Install Microsoft PowerApps CLI Tool
      run: dotnet tool install --global Microsoft.PowerApps.CLI.Tool

    - name: use pac command to list connections in UAT environment
      run: |
        pac connection list --environment "https://orga378c90d.crm.dynamics.com"
        
