name: create configuration settings
# Create Connection in higher environment
# using pac command

on:
  workflow_dispatch:

env:
#edit your values here
  ENVIRONMENT_URL: ${{ secrets.BUILD_ENVIRONMENT_URL }}
  CLIENT_ID: ${{ secrets.POWERPLATFORM_CLIENT_ID }}
  TENANT_ID: ${{ secrets.POWERPLATFORM_TENANT_ID }}
permissions:
  contents: write

jobs:
  create-settings:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1
      
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{env.BUILD_ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.POWERPLATFORMSPN }}
        tenant-id: ${{env.TENANT_ID}}

    - name: export-solution action for managed solution
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.POWERPLATFORMSPN }}
        tenant-id: ${{env.TENANT_ID}}
        managed: true
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}_managed.zip

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Adjust version if needed
 
    - name: Install Microsoft PowerApps CLI Tool
      run: dotnet tool install --global Microsoft.PowerApps.CLI.Tool

    - name: use pac command to generate Deployment settings file for UAT and Prod environment
      run: |
        pac connection list --environment "https://orga378c90d.crm.dynamics.com"
        
