name: Install xmllint
# Install xmllint

on:
  workflow_dispatch:

jobs:
  checkin-to-repo-from-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Install xmllint (libxml2)
        shell: pwsh
        run: choco install libxml2 -y
